// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActivityGetPropertiesRq struct {
	ActivityKey          string   `protobuf:"bytes,1,opt,name=ActivityKey,proto3" json:"ActivityKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityGetPropertiesRq) Reset()         { *m = ActivityGetPropertiesRq{} }
func (m *ActivityGetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*ActivityGetPropertiesRq) ProtoMessage()    {}
func (*ActivityGetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{0}
}

func (m *ActivityGetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityGetPropertiesRq.Unmarshal(m, b)
}
func (m *ActivityGetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityGetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *ActivityGetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityGetPropertiesRq.Merge(m, src)
}
func (m *ActivityGetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_ActivityGetPropertiesRq.Size(m)
}
func (m *ActivityGetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityGetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityGetPropertiesRq proto.InternalMessageInfo

func (m *ActivityGetPropertiesRq) GetActivityKey() string {
	if m != nil {
		return m.ActivityKey
	}
	return ""
}

type ActivityGetPropertiesRs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ValidStates          string   `protobuf:"bytes,5,opt,name=ValidStates,proto3" json:"ValidStates,omitempty"`
	InstanceKey          string   `protobuf:"bytes,6,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	RemoteInstance       string   `protobuf:"bytes,7,opt,name=RemoteInstance,proto3" json:"RemoteInstance,omitempty"`
	StartedDate          int64    `protobuf:"varint,8,opt,name=StartedDate,proto3" json:"StartedDate,omitempty"`
	DueDate              int64    `protobuf:"varint,9,opt,name=DueDate,proto3" json:"DueDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityGetPropertiesRs) Reset()         { *m = ActivityGetPropertiesRs{} }
func (m *ActivityGetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*ActivityGetPropertiesRs) ProtoMessage()    {}
func (*ActivityGetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{1}
}

func (m *ActivityGetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityGetPropertiesRs.Unmarshal(m, b)
}
func (m *ActivityGetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityGetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *ActivityGetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityGetPropertiesRs.Merge(m, src)
}
func (m *ActivityGetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_ActivityGetPropertiesRs.Size(m)
}
func (m *ActivityGetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityGetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityGetPropertiesRs proto.InternalMessageInfo

func (m *ActivityGetPropertiesRs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ActivityGetPropertiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetValidStates() string {
	if m != nil {
		return m.ValidStates
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetRemoteInstance() string {
	if m != nil {
		return m.RemoteInstance
	}
	return ""
}

func (m *ActivityGetPropertiesRs) GetStartedDate() int64 {
	if m != nil {
		return m.StartedDate
	}
	return 0
}

func (m *ActivityGetPropertiesRs) GetDueDate() int64 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

type ActivitySetPropertiesRs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	InstanceKey          string   `protobuf:"bytes,6,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivitySetPropertiesRs) Reset()         { *m = ActivitySetPropertiesRs{} }
func (m *ActivitySetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*ActivitySetPropertiesRs) ProtoMessage()    {}
func (*ActivitySetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{2}
}

func (m *ActivitySetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitySetPropertiesRs.Unmarshal(m, b)
}
func (m *ActivitySetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitySetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *ActivitySetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitySetPropertiesRs.Merge(m, src)
}
func (m *ActivitySetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_ActivitySetPropertiesRs.Size(m)
}
func (m *ActivitySetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitySetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitySetPropertiesRs proto.InternalMessageInfo

func (m *ActivitySetPropertiesRs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ActivitySetPropertiesRs) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ActivitySetPropertiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActivitySetPropertiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ActivitySetPropertiesRs) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ActivitySetPropertiesRs) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

type ActivityCompleteActivityRq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Option               string   `protobuf:"bytes,2,opt,name=Option,proto3" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityCompleteActivityRq) Reset()         { *m = ActivityCompleteActivityRq{} }
func (m *ActivityCompleteActivityRq) String() string { return proto.CompactTextString(m) }
func (*ActivityCompleteActivityRq) ProtoMessage()    {}
func (*ActivityCompleteActivityRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{3}
}

func (m *ActivityCompleteActivityRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityCompleteActivityRq.Unmarshal(m, b)
}
func (m *ActivityCompleteActivityRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityCompleteActivityRq.Marshal(b, m, deterministic)
}
func (m *ActivityCompleteActivityRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityCompleteActivityRq.Merge(m, src)
}
func (m *ActivityCompleteActivityRq) XXX_Size() int {
	return xxx_messageInfo_ActivityCompleteActivityRq.Size(m)
}
func (m *ActivityCompleteActivityRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityCompleteActivityRq.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityCompleteActivityRq proto.InternalMessageInfo

func (m *ActivityCompleteActivityRq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ActivityCompleteActivityRq) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

type ActivityCompleteActivityRs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityCompleteActivityRs) Reset()         { *m = ActivityCompleteActivityRs{} }
func (m *ActivityCompleteActivityRs) String() string { return proto.CompactTextString(m) }
func (*ActivityCompleteActivityRs) ProtoMessage()    {}
func (*ActivityCompleteActivityRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{4}
}

func (m *ActivityCompleteActivityRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityCompleteActivityRs.Unmarshal(m, b)
}
func (m *ActivityCompleteActivityRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityCompleteActivityRs.Marshal(b, m, deterministic)
}
func (m *ActivityCompleteActivityRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityCompleteActivityRs.Merge(m, src)
}
func (m *ActivityCompleteActivityRs) XXX_Size() int {
	return xxx_messageInfo_ActivityCompleteActivityRs.Size(m)
}
func (m *ActivityCompleteActivityRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityCompleteActivityRs.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityCompleteActivityRs proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ActivityGetPropertiesRq)(nil), "grpc.ActivityGetPropertiesRq")
	proto.RegisterType((*ActivityGetPropertiesRs)(nil), "grpc.ActivityGetPropertiesRs")
	proto.RegisterType((*ActivitySetPropertiesRs)(nil), "grpc.ActivitySetPropertiesRs")
	proto.RegisterType((*ActivityCompleteActivityRq)(nil), "grpc.ActivityCompleteActivityRq")
	proto.RegisterType((*ActivityCompleteActivityRs)(nil), "grpc.ActivityCompleteActivityRs")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_a684c9a0549e7832) }

var fileDescriptor_a684c9a0549e7832 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x69, 0xfa, 0x35, 0x62, 0x29, 0x83, 0xe8, 0x52, 0x14, 0x42, 0x0e, 0xd2, 0x53, 0x0f,
	0x7a, 0xf4, 0x24, 0x06, 0x45, 0xc4, 0x0f, 0x12, 0xe8, 0x7d, 0x4d, 0x07, 0x09, 0xb4, 0x4d, 0x9a,
	0x1d, 0x85, 0xde, 0xfc, 0x27, 0xfe, 0x02, 0xff, 0xa3, 0xec, 0xa6, 0x4b, 0xd3, 0x6a, 0x9b, 0x9b,
	0xb7, 0x99, 0x37, 0x6f, 0xde, 0xbe, 0xbe, 0x4e, 0xa0, 0x27, 0x13, 0x4e, 0x3f, 0x52, 0x5e, 0x8e,
	0xf2, 0x22, 0xe3, 0x0c, 0xbd, 0xb7, 0x22, 0x4f, 0x82, 0x2b, 0x38, 0xb9, 0x5e, 0xe1, 0x77, 0xc4,
	0x2f, 0x45, 0x96, 0x53, 0xc1, 0x29, 0xa9, 0x68, 0x81, 0x3e, 0x1c, 0xd8, 0xd1, 0x03, 0x2d, 0x85,
	0xe3, 0x3b, 0xc3, 0x6e, 0x54, 0x85, 0x82, 0x2f, 0x77, 0xd7, 0xb6, 0xc2, 0x3e, 0x34, 0xd6, 0x5b,
	0xba, 0xc4, 0x23, 0x68, 0xc6, 0x2c, 0x99, 0x84, 0xeb, 0x3b, 0xc3, 0x66, 0x54, 0x36, 0x88, 0xe0,
	0x3d, 0xc9, 0x19, 0x89, 0x86, 0x21, 0x9a, 0x5a, 0xbf, 0x1c, 0x92, 0x4a, 0x8a, 0x34, 0xe7, 0x34,
	0x9b, 0x0b, 0xaf, 0x7c, 0xb9, 0x02, 0x69, 0xc6, 0x58, 0x4e, 0xd3, 0x89, 0xd1, 0x50, 0xa2, 0x59,
	0x32, 0x2a, 0x90, 0x66, 0xdc, 0xcf, 0x15, 0xcb, 0x79, 0x42, 0xda, 0x47, 0xab, 0x64, 0x54, 0x20,
	0x3c, 0x87, 0x5e, 0x44, 0xb3, 0x8c, 0xc9, 0x82, 0xa2, 0x6d, 0x48, 0x5b, 0xa8, 0x56, 0x8a, 0x59,
	0x16, 0x4c, 0x93, 0x50, 0xbb, 0xef, 0xf8, 0xce, 0xb0, 0x11, 0x55, 0x21, 0x14, 0xd0, 0x0e, 0xdf,
	0xc9, 0x4c, 0xbb, 0x66, 0x6a, 0xdb, 0xe0, 0xdb, 0x59, 0x27, 0x14, 0xff, 0x6b, 0x42, 0x08, 0x5e,
	0x28, 0x59, 0xae, 0xa2, 0x31, 0x75, 0x7d, 0x26, 0xc1, 0x2d, 0x0c, 0xac, 0xdd, 0x9b, 0x6c, 0x96,
	0x4f, 0x89, 0xc9, 0xf6, 0xd1, 0xe2, 0x0f, 0xc7, 0xc7, 0xd0, 0x7a, 0x2e, 0x2d, 0xb8, 0x06, 0x5c,
	0x75, 0xc1, 0xe9, 0x1e, 0x1d, 0x75, 0xf1, 0xe9, 0x42, 0xc7, 0xb6, 0xf8, 0x08, 0x87, 0x1b, 0xb7,
	0x83, 0x67, 0x23, 0x7d, 0x99, 0xa3, 0x1d, 0x67, 0x39, 0xd8, 0x3b, 0x56, 0x5a, 0x2e, 0xde, 0x27,
	0xb7, 0xf5, 0x2f, 0xd4, 0xc9, 0x8d, 0xa1, 0xbf, 0xfd, 0x03, 0xd0, 0xdf, 0x5c, 0xf9, 0x1d, 0xd4,
	0xa0, 0x8e, 0xa1, 0x5e, 0x5b, 0xe6, 0x23, 0xbc, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x57, 0x1b,
	0x20, 0xa9, 0x96, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityClient interface {
	GetProperties(ctx context.Context, in *ActivityGetPropertiesRq, opts ...grpc.CallOption) (*ActivityGetPropertiesRs, error)
	SetProperties(ctx context.Context, in *ActivitySetPropertiesRs, opts ...grpc.CallOption) (*ActivityGetPropertiesRs, error)
	CompleteActivity(ctx context.Context, in *ActivityCompleteActivityRq, opts ...grpc.CallOption) (*ActivityCompleteActivityRs, error)
}

type activityClient struct {
	cc *grpc.ClientConn
}

func NewActivityClient(cc *grpc.ClientConn) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) GetProperties(ctx context.Context, in *ActivityGetPropertiesRq, opts ...grpc.CallOption) (*ActivityGetPropertiesRs, error) {
	out := new(ActivityGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Activity/GetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) SetProperties(ctx context.Context, in *ActivitySetPropertiesRs, opts ...grpc.CallOption) (*ActivityGetPropertiesRs, error) {
	out := new(ActivityGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Activity/SetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) CompleteActivity(ctx context.Context, in *ActivityCompleteActivityRq, opts ...grpc.CallOption) (*ActivityCompleteActivityRs, error) {
	out := new(ActivityCompleteActivityRs)
	err := c.cc.Invoke(ctx, "/grpc.Activity/CompleteActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
type ActivityServer interface {
	GetProperties(context.Context, *ActivityGetPropertiesRq) (*ActivityGetPropertiesRs, error)
	SetProperties(context.Context, *ActivitySetPropertiesRs) (*ActivityGetPropertiesRs, error)
	CompleteActivity(context.Context, *ActivityCompleteActivityRq) (*ActivityCompleteActivityRs, error)
}

// UnimplementedActivityServer can be embedded to have forward compatible implementations.
type UnimplementedActivityServer struct {
}

func (*UnimplementedActivityServer) GetProperties(ctx context.Context, req *ActivityGetPropertiesRq) (*ActivityGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperties not implemented")
}
func (*UnimplementedActivityServer) SetProperties(ctx context.Context, req *ActivitySetPropertiesRs) (*ActivityGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperties not implemented")
}
func (*UnimplementedActivityServer) CompleteActivity(ctx context.Context, req *ActivityCompleteActivityRq) (*ActivityCompleteActivityRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteActivity not implemented")
}

func RegisterActivityServer(s *grpc.Server, srv ActivityServer) {
	s.RegisterService(&_Activity_serviceDesc, srv)
}

func _Activity_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityGetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Activity/GetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetProperties(ctx, req.(*ActivityGetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_SetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitySetPropertiesRs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).SetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Activity/SetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).SetProperties(ctx, req.(*ActivitySetPropertiesRs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_CompleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityCompleteActivityRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CompleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Activity/CompleteActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CompleteActivity(ctx, req.(*ActivityCompleteActivityRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProperties",
			Handler:    _Activity_GetProperties_Handler,
		},
		{
			MethodName: "SetProperties",
			Handler:    _Activity_SetProperties_Handler,
		},
		{
			MethodName: "CompleteActivity",
			Handler:    _Activity_CompleteActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
